version: '3.0'

services:
  mysql:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: epsiroot
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./src/db/:/docker-entrypoint-initdb.d
    ports:
      - '${MYSQL_PORT}:3306'