# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v2
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

    - # ... some steps before set-up MySQL ...
    - name: Set up MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        mysql database: 'epsi' # Optional, default value is "test". The specified database which will be create
        mysql user: 'epsi' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"
    - name: Verify MariaDB connection
      run: |
        mysql --host 0.0.0.0 --port 3306 -u epsi -p${{ secrets.DatabasePassword }} < src/db/create-db.sql
        mysql --host 0.0.0.0 --port 3306 -u epsi -p${{ secrets.DatabasePassword }} -e "SHOW DATABASES"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      env:
        DB_HOST: mysql
        DB_DATABASE: epsi
        DB_USER: epsi
        DB_PASS: ${{ secrets.DatabasePassword }}
        SECRET_JWT: supersecret
        PORT: 3000
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
